import {
  fileConfig,
  CI_PILOT_CONFIG_FILE_PATH,
  FEATURE_BRANCH_REGEX,
  LERNA_CONFIG_FILE_PATH,
  NPM_CONFIG_REGISTRY,
  PACKAGE_JSON_FILE_PATH,
  PACKAGE_ROOT_PATH,
  REPO_ROOT_PATH,
  ROOT_PACKAGE_JSON_FILE_PATH,
  SEMVER_ALPHA_PRERELEASE_ID_PREFIX,
  SEMVER_FEATURE_PRERELEASE_ID_PREFIX,
  DEV_MODE,
  PACKAGE_JSON_FILE,
  CWD,
} from './config';
import { defaultBranches } from './helpers';

const out = {
  NPM_CONFIG_REGISTRY,

  PACKAGE_ROOT_PATH,
  REPO_ROOT_PATH,
  ROOT_PACKAGE_JSON_FILE_PATH,
  PACKAGE_JSON_FILE_PATH,
  LERNA_CONFIG_FILE_PATH,
  CI_PILOT_CONFIG_FILE_PATH,
  FEATURE_BRANCH_REGEX,
  SEMVER_FEATURE_PRERELEASE_ID_PREFIX,
  SEMVER_ALPHA_PRERELEASE_ID_PREFIX,
  DEV_MODE,
  PACKAGE_JSON_FILE,
  CWD,

  ...fileConfig,

  defaultBranches,
};

export default out;
